ProjectoAJP/ProjectoAJP/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [url(r'^vendas/', include('vendas.urls')),
                    url(r'^admin/', admin.site.urls), ]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ProjectoAJP/vendas/urls.py
from django.conf.urls import url
from . import views

app_name = 'vendas'
urlpatterns = [url(r'^$', views.index, name='index'),

url(r'^Administrador/$', views.Administrador, name='Administrador'),
url(r'^pesquisa/$', views.pesquisa, name='pesquisa'),
url(r'^(?P<carro_id>[0-9]+)/FormularioCompra/$', views.FormularioCompra, name='FormularioCompra'),
url(r'^(?P<carro_id>[0-9]+)/pagamentoRemover/$', views.pagamentoRemover, name='pagamentoRemover'),
url(r'^StoqueCarro/$', views.StoqueCarro, name='StoqueCarro'),
url(r'^contact_us/$', views.contact_us, name='contact_us'),
url(r'^about_us/$', views.about_us, name='about_us'),
url(r'^how_to_buy/$', views.how_to_buy, name='how_to_buy'),
url(r'^quality/$', views.quality, name='quality'),
url(r'^spare_parts/$', views.spare_parts, name='spare_parts'),
url(r'^distributors/$', views.distributors, name='distributors'),
url(r'^loginview/$', views.loginview, name='loginview'),
url(r'^logoutview/$', views.logoutview, name='logoutview'),
url(r'^paginalogin/$', views.paginalogin, name='paginalogin'),
url(r'^envia_email/$', views.envia_email, name='envia_email'),
url(r'^adicionarCarro/$', views.adicionarCarro, name='adicionarCarro'),
url(r'^guardarCarro/$', views.guardarCarro, name='guardarCarro'),


url(r'^RemoverCarro/$', views.RemoverCarro, name='RemoverCarro'),
url(r'^apagarCarro/$', views.apagarCarro, name='apagarCarro'),
url(r'^simple_upload/$', views.simple_upload, name='simple_upload'),
url(r'^Carronexiste/$', views.Carronexiste, name='Carronexiste'),

url(r'^utilizador/$', views.utilizador, name='utilizador'),
url(r'^utilizadorAU/$', views.utilizadorAU, name='utilizadorAU'),
url(r'^InformacaoUtilizador/$', views.InformacaoUtilizador, name='InformacaoUtilizador'),
url(r'^guardarUtilizador/$', views.guardarUtilizador, name='guardarUtilizador'),
url(r'^paginaregisto/$', views.paginaregisto, name='paginaregisto'),
url(r'^(?P<cliente_id>[0-9]+)/alterar/$', views.alterar, name='alterar'),

url(r'^questao/$', views.questao, name='questao'),
url(r'^guardarQ/$', views.guardarQ, name='guardarQ'),
url(r'^(?P<questao_id>[0-9]+)/resposta/$', views.resposta, name='resposta'),
url(r'^passaPergResp/$', views.passaPergResp, name='passaPergResp'),

]

ProjectoAJP/vendas/models.py

from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.db import models
from django.utils import timezone
import datetime

class Carro(models.Model):
    marca= models.CharField(max_length=200)
    modelo = models.CharField(max_length=200)
    matricula = models.CharField(max_length=200)
    ano_fabrico = models.IntegerField()
    distancia_percorrida = models.IntegerField()
    preco=models.IntegerField()
    imagem = models.CharField(max_length=200)



    def get_marca(self):
        return self.marca

    def get_modelo(self):
        return self.modelo

    def get_matricua(self):
        return self.matricula

    def get_ano_fabrico(self):
        return self.ano_fabrico

    def get_distancia_percorrida(self):
        return self.distancia_percorrida

    def get_preco(self):
        return self.preco

    def get_imagem(self):
        return self.imagem\

    def __str__(self):
        return (self.marca + ', ' + self.modelo + ', ' + self.matricula +', ' + str(self.ano_fabrico) + ', '
                + str(self.distancia_percorrida) +', ' + str(self.preco) +', ' + self.imagem)


class Cliente (models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=200)
    apelido = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    morada = models.CharField(max_length=200)
    telefone = models.IntegerField()

    def get_Nome(self):
        return self.nome

    def get_Apelido(self):
        return self.apelido

    def get_Email(self):
        return self.email

    def get_Morada(self):
        return self.morada

    def get_Telefone(self):
        return self.telefone

    def __str__(self):
        return "nome: %s, apelido: %s, email: %s, morada: %s, telefone: %d, username: %s" \
               %(self.nome, self.apelido, self.email,self.morada, self.telefone, self.username)

class Resposta(models.Model):
    texto=models.CharField(max_length=200)

    def __str__(self):
        return self.texto

class Questao(models.Model):
    resposta = models.OneToOneField(Resposta, on_delete=models.CASCADE)
    questao_texto = models.CharField(max_length=200)
    pub_data =models.DateTimeField('data de publicacao')

    def foi_publicada_recentemente(self):
        return self.pub_data >= timezone.now()-datetime.timedelta(days=1)

    def __str__(self):
        return self.questao_texto




ProjectoAJP/vendas/views.py
from django.utils import timezone
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse,HttpResponseRedirect
from .models import Cliente, Carro
from .models import Questao, Resposta
from django.template import loader
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login , logout
from django.conf import settings
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage
from django.core.mail import BadHeaderError, send_mail
import os


def Administrador(request):
    return render(request, 'vendas/Administrador.html')

def index(request):
    latest_vendas_list = Carro.objects.all()
    context = {'latest_vendas_list': latest_vendas_list}
    return render(request, 'vendas/index.html', context)

def pesquisa(request):
    marcast= request.POST['marca']
    resultadoCarro=Carro.objects.filter(marca=marcast.lower())
    context = {'resultadoCarro': resultadoCarro}
    return render(request,'vendas/pesquisa.html',context)

def FormularioCompra(request, carro_id):
    c = Carro.objects.get(id=carro_id)
    context = {'carro': c}
    return render(request, 'vendas/FormularioCompra.html', context)

def Carronexiste(request):
    return render(request, 'vendas/CarroNexiste.html')

def pagamentoRemover(request, carro_id):
    envia_email(request, carro_id)
    return render(request, 'vendas/index.html')


def adicionarCarro(request):
    if not request.user.is_superuser:
        return render(request, 'vendas/index.html')
    else:
        return render(request, 'vendas/adicionarCarro.html')

def guardarCarro(request):
    marc = request.POST['marca']
    model = request.POST['modelo']
    matric = request.POST['matricula']
    anoFaric = request.POST['ano_fabrico']
    distpercoric = request.POST['distancia_percorrida']
    prec=request.POST['preco']
    c=Carro(marca=marc,modelo=model,matricula=matric,ano_fabrico=anoFaric,
            distancia_percorrida=distpercoric,preco=prec, imagem=filename)
    c.save()
    return HttpResponseRedirect(reverse('vendas:StoqueCarro'))


def RemoverCarro(request):
    if not request.user.is_superuser:
        return render(request, 'vendas/index.html')
    else:
        return render(request, 'vendas/RemoverCarro.html')

def apagarCarro(request):
    strmarcas = request.POST['matricula']
    if Carro.objects.filter(matricula=strmarcas).exists():
        Carro.objects.get(matricula=strmarcas).delete()
        return HttpResponseRedirect(reverse('vendas:StoqueCarro'))
    else:
        return render(request, 'vendas/CarroNExiste.html')


def StoqueCarro(request):
    resultadoCarro = Carro.objects.all()
    context = {'resultadoCarro': resultadoCarro}
    return render(request, 'vendas/StoqueCarro.html', context)

def about_us(request):
    return render(request, 'vendas/About_US.html')

def how_to_buy(request):
    return render(request, 'vendas/How_to_Buy.html')

def quality(request):
    return render(request, 'vendas/Quality.html')

def spare_parts(request):
    return render(request, 'vendas/Spare_Parts.html')

def contact_us(request):
    return render(request, 'vendas/contactos.html')

def distributors(request):
    return render(request, 'vendas/Distributors.html')

def paginalogin(request):
    return render(request, 'vendas/paginalogin.html')

def loginview(request):
    try:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
        u=User.objects.get(username=username)
    except( KeyError, User.DoesNotExist):
        return render(request, 'vendas/paginalogin.html', {'error_messages':'user does not exists'})
    else:
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('vendas:index'), {'notificacao': 'loggin efetuado com sucesso'})
        else:
            return render(request,'vendas/paginalogin.html',{'error_message':'wrong password'})


def logoutview(request):
    logout(request)
    return HttpResponseRedirect(reverse('vendas:index'),{'sucesso':'sucesso no logout'})

def umaview(request):
    if not request.user.is_authenticated:
        return render(request,'umaapp/login_error.html')

def envia_email(request, carro_id):
    c = Carro.objects.get(id=carro_id)
    destino= request.POST['email_addr']
    apelido = request.POST['SobreNome']
    Assunto="Caro Sr(a)." + apelido + ", enviamos este recibo como forma de confirmar o pagamento do" \
                                      " carro com a Marca:"+ c.marca +" ,Matricula: "+ c.matricula
    send_mail('Recibo do carro', Assunto , settings.EMAIL_HOST_USER , [destino],fail_silently=False)
    Carro.objects.get(id=carro_id).delete()
    return HttpResponseRedirect(reverse('vendas:index'))


def simple_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        marc = request.POST['marca']
        model = request.POST['modelo']
        matric = request.POST['matricula']
        anoFaric = request.POST['ano_fabrico']
        distpercoric = request.POST['distancia_percorrida']
        prec = request.POST['preco']
        c = Carro(marca=marc, modelo=model, matricula=matric, ano_fabrico=anoFaric,
                  distancia_percorrida=distpercoric, preco=prec, imagem=filename)
        c.save()
        return render(request,'vendas/index.html',{'uploaded_file_url':   uploaded_file_url})

    return render(request, 'vendas/index.html')

def utilizador(request):
    return render(request, 'vendas/Utilizador.html')

def utilizadorAU(request):
    try:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
        #u=User.objects.get(username=username)
        print ('**************** ' +str(user))
        c=Cliente.objects.get(user=user)
        contexto={'util': c}
    except( KeyError, User.DoesNotExist):
        return render(request, 'vendas/paginalogin.html', {'error_messages':'user does not exists'})
    else:
        if user is not None:
            return render(request,'vendas/utilizadorAU.html', contexto)
        else:
            return render(request,'vendas/paginalogin.html',{'error_message':'wrong password'})



def InformacaoUtilizador(request):
    n = request.POST['Nome']
    apel = request.POST['SobreNome']
    emai = request.POST['email_addr']
    morad = request.POST['Morada']
    telef = request.POST['Telefone']
    username = request.POST['username']
    password = request.POST['password']
    use = User.objects.create_user(username,emai,password)
    #use.save()
    c = Cliente(user=use, nome=n, apelido=apel, email=emai, morada=morad,telefone=telef)
    c.save()
    return render(request,'vendas/index.html')


def guardarUtilizador(request):
    nom = request.POST['nome']
    apel = request.POST['sobreNome']
    emai = request.POST['email']
    morad = request.POST['morada']
    telef = request.POST['telefone']
    c = Cliente(nome=nom, apelido=apel, email=emai, morada=morad,
                telefone=telef)
    c.save()
    return HttpResponseRedirect(reverse('vendas:utilizador'))

def paginaregisto(request):
    return render(request, 'vendas/paginaregisto.html')

def alterar(request, cliente_id):
    c = Cliente.objects.get(pk=cliente_id)
    c.nome = request.POST['nome']
    c.apelido = request.POST['SobreNome']
    c.email = request.POST['email_addr']
    c.morada = request.POST['Morada']
    c.telefone = request.POST['Telefone']
    c.save()
    return render(request, 'vendas/n.html', {'cliente': c})

def questao(request):
    latest = Questao.objects.all()
    context = {'perguntas': latest}
    return render(request, 'vendas/questao.html', context)

def guardarQ(request):
    latest = Questao.objects.all()
    context = {'perguntas': latest}
    q = request.POST['questaos']
    respost=Resposta(texto=' ')
    respost.save()
    questao =Questao(questao_texto=q, pub_data=timezone.now(), resposta=respost)
    questao.save()
    return render(request, 'vendas/questao.html', context)

def resposta(request, questao_id):
    latest_question_list = Questao.objects.all()
    context = {'perguntas': latest_question_list}
    q= Questao.objects.get(pk=questao_id)
    r= request.POST['resposta']
    res=Resposta(texto=r)
    q.resposta =res
    res.save()
    return render(request, 'vendas/questao.html', context )

def passaPergResp(request):
 latest_question_list = Questao.objects.all()
 context = {'perguntas': latest_question_list}
 return render(request, 'vendas/.html', context)



ProjectoAJP/vendas/templates/vendas/CarroNExiste.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p> Carro nao existe na nossa base de dados</p>
 <li><a href="{% url 'vendas:index' %}">Volte clicando aqui</a></li>

</body>
</html>

ProjectoAJP/vendas/templates/vendas/RemoverCarro.html
<style type="text/css">
            body {background-color:lightBlue;}
            p {color:blue;}


form {
  width:300px;
  margin: 20px auto;
}

input {
  border:1px solid #ccc;
  font-size:20px;
  width:300px;
  min-height:30px;
  display:block;
  margin-bottom:15px;
  margin-top:5px;
  outline: none;
}

input[type=submit] {
  background:none;
  padding:10px;
}
</style>

     <footer>
        <p align="center">
            DADOS DO CARRO
        </p>

    </footer>
        <form name="input" action="{% url 'vendas:apagarCarro'%}" method="post">
            {% csrf_token %}

         <label>Matricula:</label>
          <input type="matricula" id="matricula" name="matricula" required>

            <input type="submit" value="Gravar Carro e voltar a lista" />
    </form>


ProjectoAJP/vendas/templates/vendas/StoqueCarro.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css"
href="{% static 'vendas/style.css' %}"/>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>

    <header class="menu-principalBarraPreta">
    <main>
        <nav class="logo">
        <a href="{% url 'vendas:index' %}"><img src="../../static/vendas/imagens/trust-japanesevehicles-logo.png" alt="JaponeseVechicles.pt"
        width="100" height="70"></a>
        </nav>

        <nav class=" redes-sociais">
            <ul>
                <li>
                <a href=""><img src="../../static/vendas/imagens/rcss.png" alt="" width="20" height="20"> </a>
                </li>
                <li>
                <a href="https://www.facebook.com/JapaneseVehicles"><img src="../../static/vendas/imagens/facebook.jpg" alt="" width="20" height="20"></a>
                </li>
                <li>
                <a href=""><img src="../../static/vendas/imagens/twiter.png"alt="" width="20" height="20" ></a>
                </li>
                <li>
                <a href=""><img src="../../static/vendas/imagens/linkedin.png" alt="" width="20" height="20"> </a>
                </li>
                <li>
                <a href=""><img src="../../static/vendas/imagens/instagram.png" alt="" width="20" height="20"> </a>
                </li>
            <br />
                <font color="#fff">
                EMAIL:sales@japcar.com
                <br/>
                TEL:+351-222-219-245
                <br/>
                <form action="{% url 'vendas:paginalogin' %}" method="post">
                {% csrf_token %}
                Já és membro?:<input type="submit" value="Fazer Login"/>
                </form>
                <form action="{% url 'vendas:paginaregisto' %}" method="post">
                {% csrf_token %}
                Não és membro?:<input type="submit" value="Fazer Registo"/>
                </form>

                {% if sucesso %}
                <font color="#fff">
                <p>{{sucesso}}</p>
                {% endif %}
                </font>
                </font>
            </ul>
        </nav>
    </main>
    </header>
    <br>

        <nav class="menus">
            <nav class = "menu">
                <ul>
                    <li><a href="{% url 'vendas:index' %}">HOME</a></li>
                    <li><a href="{% url 'vendas:StoqueCarro' %}">Stocklist</a> </li>
                    <li><a href="{% url 'vendas:about_us' %}">About us</a> </li>
                    <li><a href="{% url 'vendas:how_to_buy' %}">How to buy</a> </li>
                    <li><a href="{% url 'vendas:quality' %}">Quality</a> </li>
                    <li><a href="{% url 'vendas:contact_us' %}">Contact us</a> </li>
                    <li><a href="{% url 'vendas:Administrador' %}">Administrador</a> </li>
                    <li><a href="{% url 'vendas:utilizador' %}">Utilizador</a> </li>
                </ul>
            </nav>
        </nav>

        <nav class="busca">
                <ul>
                    {% for vendas in latest_vendas_list %}

                    {% endfor %}
                    <form action="{% url 'vendas:pesquisa'%}" method="post">
                    {% csrf_token %}
                    <p>Procura por marca: <input type="text" name="marca"> <input type="submit" value="Pesquisar" /></p>

                    </form>
                </ul>
        </nav>
        <br/>
        <br/>

        <nav class="tabelacarros">
            <ul>
                {% for vendas in resultadoCarro %}

                <a>
                <table border="0">
                <tr>
                <td><p>Imagem</p></td>
                <td><p>Dados do Carro</p></td>
                </tr>
                <tr>

                <td><p><img src="../../static/vendas/imagens/{{vendas.imagem}}"
                width="300" height="200"></p>
                {% csrf_token %}

                <br />

                <li>
                --------------------------------------------------------------------
                </li>
                </td>
                <td><p>Marca:{{ vendas.marca}} <br/>Modelo:{{ vendas.modelo}}<br/>
                Ano de Fabrico:{{ vendas.ano_fabrico}}<br/>
                Distancia Percorrida:{{vendas.distancia_percorrida}}<br/>
                Matricula:{{ vendas.matricula}}<br/>
                Preço:{{vendas.preco}}<br/>
                </p>

                </tr>

                </table>
                </a>
                {% endfor %}

            </ul>
        </nav>

            <form action="{% url 'vendas:index' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Voltar" />
            <br>
            </form>

            {% for vendas in resultadoCarro %}

            <form action="{% url 'vendas:FormularioCompra' vendas.id %}">
            <input type="radio" name="carro"/>
            <br />
            {% endfor %}
            <p> <input type="submit" value="COMPRAR" /></p>
            </form>






ProjectoAJP/vendas/templates/vendas/Utilizador.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css"
href="{% static 'vendas/style.css' %}"/>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>

    <header class="menu-principalBarraPreta">
    <main>
        <nav class="logo">
        <a href="{% url 'vendas:index' %}"><img src="../../static/vendas/imagens/trust-japanesevehicles-logo.png" alt="JaponeseVechicles.pt"
        width="100" height="70"></a>
        </nav>

        <nav class=" redes-sociais">
            <ul>
                <li>
                <a href=""><img src="../../static/vendas/imagens/rcss.png" alt="" width="20" height="20"> </a>
                </li>
                <li>
                <a href="https://www.facebook.com/JapaneseVehicles"><img src="../../static/vendas/imagens/facebook.jpg" alt="" width="20" height="20"></a>
                </li>
                <li>
                <a href=""><img src="../../static/vendas/imagens/twiter.png"alt="" width="20" height="20" ></a>
                </li>
                <li>
                <a href=""><img src="../../static/vendas/imagens/linkedin.png" alt="" width="20" height="20"> </a>
                </li>
                <li>
                <a href=""><img src="../../static/vendas/imagens/instagram.png" alt="" width="20" height="20"> </a>
                </li>
            <br />
                <font color="#fff">
                EMAIL:sales@japcar.com
                <br/>
                TEL:+351-222-219-245
                <br/>
                <form action="{% url 'vendas:paginalogin' %}" method="post">
                {% csrf_token %}
                Já és membro?:<input type="submit" value="Fazer Login"/>
                </form>
                <form action="{% url 'vendas:paginaregisto' %}" method="post">
                {% csrf_token %}
                Não és membro?:<input type="submit" value="Fazer Registo"/>
                </form>

                {% if sucesso %}
                <font color="#fff">
                <p>{{sucesso}}</p>
                {% endif %}
                </font>
                </font>
            </ul>
        </nav>
    </main>
    </header>
    <br>

        <nav class="menus">
            <nav class = "menu">
                <ul>
                    <li><a href="{% url 'vendas:index' %}">HOME</a></li>
                    <li><a href="{% url 'vendas:StoqueCarro' %}">Stocklist</a> </li>
                    <li><a href="{% url 'vendas:about_us' %}">About us</a> </li>
                    <li><a href="{% url 'vendas:how_to_buy' %}">How to buy</a> </li>
                    <li><a href="{% url 'vendas:quality' %}">Quality</a> </li>
                    <li><a href="{% url 'vendas:contact_us' %}">Contact us</a> </li>
                    <li><a href="{% url 'vendas:Administrador' %}">Administrador</a> </li>
                    <li><a href="{% url 'vendas:utilizador' %}">Utilizador</a> </li>
                </ul>
            </nav>
        </nav>

        <nav class="busca">
                <ul>
                    {% for vendas in latest_vendas_list %}

                    {% endfor %}
                    <form action="{% url 'vendas:pesquisa'%}" method="post">
                    {% csrf_token %}
                    <p>Procura por marca: <input type="text" name="marca"> <input type="submit" value="Pesquisar" /></p>

                    </form>
                </ul>
        </nav>
        <br/>
        <br/>
        <nav class="Papel-FundoLetra" >

                <form action="{% url 'vendas:utilizadorAU'%}" method="post">
                {% csrf_token %}
                <p><h1 align="center">User_name: <input type="text" name="username">
                <p>Password: <input type="password" name="password">
                <br/><br/>
                <input type="submit" value="Go" /></h1></p>
                </form>

        </nav>

ProjectoAJP/vendas/templates/vendas/paginalogin.html

<style type="text/css">
            body {background-color:lightBlue;}
            p {color:blue;}


            form {
              width:300px;
              margin: 20px auto;
            }

            input {
              border:1px solid #ccc;
              font-size:20px;
              width:300px;
              min-height:30px;
              display:block;
              margin-bottom:15px;
              margin-top:5px;
              outline: none;
            }

            input[type=submit] {
              background:none;
              padding:10px;
            }

</style>
<form action="{% url 'vendas:loginview'%}" method="post">
                 {% csrf_token %}
                    <p>User_name: <input type="text" name="username">
                    <p>Password: <input type="password" name="password">
                    <br>
                    <input type="submit" value="Login" /></p>
             </form>

            <form action="{% url 'vendas:logoutview' %}" method="post">
                 {% csrf_token %}
                    <input type="submit" value="Logout" /></p>
             </form>

            {% if error_message %}
            <p>{{error_message}}</p>
            {% endif %}

            {% if error_messages %}
            <p>{{error_messages}}</p>
                    {% endif %}

            {% if notificacao %}
            <p>{{notificacao}}</p>
            {% endif %}

            {% if sucesso %}
            <p>{{sucesso}}</p>
            {% endif %}

ProjectoAJP/vendas/templates/vendas/questao.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css"
href="{% static 'vendas/style.css' %}"/>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>

    <header class="menu-principalBarraPreta">
    <main>
        <nav class="logo">
        <a href="{% url 'vendas:index' %}"><img src="../../static/vendas/imagens/trust-japanesevehicles-logo.png" alt="JaponeseVechicles.pt"
        width="100" height="70"></a>
        </nav>

        <nav class=" redes-sociais">
            <ul>
                <li>
                <a href=""><img src="../../static/vendas/imagens/rcss.png" alt="" width="20" height="20"> </a>
                </li>
                <li>
                <a href="https://www.facebook.com/JapaneseVehicles"><img src="../../static/vendas/imagens/facebook.jpg" alt="" width="20" height="20"></a>
                </li>
                <li>
                <a href=""><img src="../../static/vendas/imagens/twiter.png"alt="" width="20" height="20" ></a>
                </li>
                <li>
                <a href=""><img src="../../static/vendas/imagens/linkedin.png" alt="" width="20" height="20"> </a>
                </li>
                <li>
                <a href=""><img src="../../static/vendas/imagens/instagram.png" alt="" width="20" height="20"> </a>
                </li>
            <br />
                <font color="#fff">
                EMAIL:sales@japcar.com
                <br/>
                TEL:+351-222-219-245
                <br/>
                <form action="{% url 'vendas:paginalogin' %}" method="post">
                {% csrf_token %}
                Já és membro?:<input type="submit" value="Fazer Login"/>
                </form>
                <form action="{% url 'vendas:paginaregisto' %}" method="post">
                {% csrf_token %}
                Não és membro?:<input type="submit" value="Fazer Registo"/>
                </form>

                {% if sucesso %}
                <font color="#fff">
                <p>{{sucesso}}</p>
                {% endif %}
                </font>
                </font>
            </ul>
        </nav>
    </main>
    </header>
    <br>

        <nav class="menus">
            <nav class = "menu">
                <ul>
                    <li><a href="{% url 'vendas:index' %}">HOME</a></li>
                    <li><a href="{% url 'vendas:StoqueCarro' %}">Stocklist</a> </li>
                    <li><a href="{% url 'vendas:about_us' %}">About us</a> </li>
                    <li><a href="{% url 'vendas:how_to_buy' %}">How to buy</a> </li>
                    <li><a href="{% url 'vendas:quality' %}">Quality</a> </li>
                    <li><a href="{% url 'vendas:contact_us' %}">Contact us</a> </li>
                    <li><a href="{% url 'vendas:Administrador' %}">Administrador</a> </li>
                    <li><a href="{% url 'vendas:utilizador' %}">Utilizador</a> </li>


                </ul>
            </nav>
        </nav>

        <nav class="busca">
                <ul>
                    {% for vendas in latest_vendas_list %}

                    {% endfor %}
                    <form action="{% url 'vendas:pesquisa'%}" method="post">
                    {% csrf_token %}
                    <p>Procura por marca: <input type="text" name="marca"> <input type="submit" value="Pesquisar" /></p>

                    </form>
                </ul>
        </nav>
        <br/>
        <br/>

    <form name="input" action="{% url 'vendas:guardarQ' %}" method="post">
        {% csrf_token %}
        <p>Questao: <input type="text" name="questaos"></p>
        <input type="submit" value="Gravar questao e voltar a lista" />
    </form>

     {% for  p in perguntas %}
       {{ p.questao_texto }}
        {{p.resposta }}


     <br>



    <form  action="{% url 'vendas:resposta' p.id %}" method="post">
        {% csrf_token %}
        <p>Resposta: <input type="text" name="resposta"></p>
        <input type="submit" value="Gravar resposta e voltar a lista" />
        {% endfor %}

    </form>







